import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uifry | Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="scroll-smooth scrollbar-w-2 scrollbar
    scrollbar-thumb-red hover:scrollbar-thumb-[#9f9f9f]"
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
